version: '3.7'

services:
  postgres:
    image: postgres:13
    container_name: postgres_rabbitmq
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: postgres_rabbitMQ
      POSTGRES_PASSWORD: postgres_rabbitMQ
      POSTGRES_DB: postgres_rabbitMQ
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
